import { signIn, signOut, useSession } from "next-auth/react";
import React, { useState } from "react";

import { type Recepty } from "@prisma/client";
import Link from "next/link";
import Layout from "../components/Layout";
import { api } from "../utils/api";

import Image from "next/image";
import { FaClock, FaSignal, FaUsers } from "react-icons/fa";
import { FiAlertTriangle } from "react-icons/fi";
import { BounceLoader } from "react-spinners";

function Home() {
  const getRecipes = api.recipes.getAll.useQuery();
  const options = api.options.getAll.useQuery().data;
  const [recipes, setRecipes] = useState<Recepty[]>();

  const Dificulty = (dificulty: string) => {
    switch (dificulty) {
      case "EASY":
        return "Snadná";
      case "MEDIUM":
        return "Střední";
      case "HARD":
        return "Těžká";
      case "EXTRAHARD":
        return "Extrémně těžká";
    }
  };

  if (getRecipes.data && !recipes) {
    const recipes = getRecipes.data;
    setRecipes([...recipes]);
  }
  if (options?.underConstruction)
    return (
      <Layout>
        <FiAlertTriangle size={200} className="text-yellow-300" />
        <h1 className="text-4xl">
          Pracuji na vylepšení webu brzy bude znovu k dispozici
        </h1>
      </Layout>
    );
  return (
    <>
      {/* <Head>
        <title>{options?.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-6 py-16 ">
          <h1 className="sm:text-[5rem]">
            {options?.name}{" "}
            <span className="text-[hsl(280,100%,70%)]">Kuchařka</span>
          </h1>
          <h2 className="text-3xl">Recepty: </h2>
          {getRecipes.isLoading && (
            <div className="flex flex-col items-center justify-center gap-5">
              <BounceLoader color="#786298" />
              <p className="text-xs font-extralight uppercase tracking-widest">
                Načítám recepty...
              </p>
            </div>
          )}
          <div className="flex h-full w-full max-w-5xl flex-col items-center justify-center gap-4">
            {recipes ? (
              recipes.map((recipe, i) => {
                return (
                  <Link
                    href={`/recipe/${recipe.id}`}
                    className="w-full"
                    key={recipe.id}
                  >
                    <div
                      key={i}
                      className="relative 
                      grid grid-cols-1 justify-start gap-4 
                      overflow-hidden rounded-lg p-4 text-white transition-all 
                      nm-flat-gray-900 hover:nm-flat-gray-900-sm md:h-80 md:grid-cols-2"
                    >
                      <div className="relative block h-72 w-full items-center justify-center">
                        <Image
                          src={recipe.imgUrl}
                          fill
                          className="rounded-xl object-cover"
                          alt={recipe.title}
                        />
                      </div>
                      <div className="flex w-full flex-col items-center justify-center">
                        <h1 className="text-5xl md:text-4xl lg:text-5xl">
                          {recipe.title}
                        </h1>
                        <div className="my-4 grid grid-cols-3 place-items-center justify-center gap-4 rounded-md bg-white/20 p-2">
                          <span className="flex flex-col items-center justify-center gap-1">
                            <FaClock size={20} />
                            {recipe.time} min.
                          </span>
                          <span className="flex flex-col items-center justify-center gap-1">
                            <FaSignal size={20} />
                            {Dificulty(recipe.difficulty)}
                          </span>
                          <span className="flex flex-col items-center justify-center gap-1">
                            <FaUsers size={20} />
                            {recipe.portions}
                          </span>
                        </div>
                        <p>Zobrazit recept</p>
                      </div>
                    </div>
                  </Link>
                );
              })
            ) : (
              <></>
            )}
          </div>
          <div className="flex flex-col items-center justify-center gap-4"></div>
          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const role = api.example.getUserRole.useQuery(undefined, {
    enabled: sessionData?.user !== undefined,
  }).data?.role;

  return (
    <div className="fixed bottom-0 flex w-full flex-row items-center justify-between gap-4 bg-black/70 px-6 py-2">
      <p className="flex flex-row items-center justify-center gap-2 text-center text-white">
        {sessionData && (
          <span className="text-lg">{sessionData.user?.name}</span>
        )}
        <Link href="/admin">
          <span className="text-center text-xs text-red-500">
            {role && <span> - {role}</span>}
          </span>
        </Link>
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
